Passing client headers on connection setup
scalecube/scalecube-gateway pull request #135
Opened 2020-05-24 18:00 UTC by segabriel

Closes #131

2020-05-24 20:06 UTC, artem-v requested changes
Plz add test on http as well.

2020-05-24 20:06 UTC, artem-v commented on services-gateway-client-transport/src/main/java/io/scalecube/services/gateway/transport/GatewayClientSettings.java
> +      this.headers = Map.copyOf(originalSettings.headers);
Plz dont use java 11 API (so far)

2020-05-24 20:06 UTC, artem-v commented on services-gateway-client-transport/src/main/java/io/scalecube/services/gateway/transport/GatewayClientSettings.java
> +      this.headers = Map.copyOf(headers);
Plz dont use java 11 API (so far)

2020-05-24 20:06 UTC, artem-v commented on services-gateway-netty/src/main/java/io/scalecube/services/gateway/rsocket/RSocketGatewaySession.java
> +    this.headers = Map.copyOf(headers);
Plz dont use java 11 API (so far)

2020-05-24 20:06 UTC, artem-v commented on services-gateway-netty/src/main/java/io/scalecube/services/gateway/ws/WebsocketGatewaySession.java
> +    this.headers = Map.copyOf(headers);
Plz dont use java 11 API (so far)

2020-05-24 20:16 UTC, segabriel commented
@artem-v http is not implemented at all, needs lots of work to add it, and refactor existing code.

2020-05-25 06:39 UTC, artem-v commented
> @artem-v HTTP is not implemented at all, it needs lots of work to add it and refactor existing code.
> Probably better is creating an issue about HTTP.

Ok. Plz go ahead and create HTTP issue/story.

2020-05-25 06:41 UTC, segabriel commented
@artem-v done https://github.com/scalecube/scalecube-gateway/issues/136

2020-05-25 06:46 UTC, artem-v commented
> @artem-v done #136

Also created https://github.com/scalecube/scalecube-gateway/issues/137

2020-05-25 06:46 UTC, artem-v approved these changes

2020-05-25 06:47 UTC, merged