Extend client sdk
scalecube/scalecube-gateway pull request #20
Opened 2019-06-14 13:17 UTC by segabriel

2019-06-14 17:03 UTC, ronenhamias commented on pom.xml
> +    <module>services-gateway-clientTransport</module>
this should be named services-gateway-client-transport

2019-06-14 17:07 UTC, ronenhamias commented on services-gateway-benchmarks/src/main/java/io/scalecube/services/benchmarks/gateway/InfiniteStreamScenario.java
> +  private static ServiceMessage enichResponse(ServiceMessage msg) {
threre is typo here

2019-06-17 08:40 UTC, snripa approved these changes

2019-06-20 14:27 UTC, dmytro-lazebnyi commented
I found the following example of usage in `AbstractGatewayExtension`:

```
    Address address = this.gateway.gateway(gatewayId).address();
    client = Microservices.builder()
        .transport(op -> clientSupplier.apply(
            GwClientSettings.builder().address(address).loopResources(clientLoopResources).build(),
            op))
        .startAwait();

    serviceCall = client.call().router(new StaticAddressRouter(address));
```

So, if I understood correctly, now to call gateway I need to do following steps on *caller side*:
1. Add dependency to whole `scalecube-services` module.
2. Build and start new `Microservices`.
3. Create `ServiceCall`.

Looks too overhead as for me.

2019-06-21 10:03 UTC, ronenhamias commented
> I found the following example of usage in `AbstractGatewayExtension`:
> 
> ```
>     Address address = this.gateway.gateway(gatewayId).address();
>     client = Microservices.builder()
>         .transport(op -> clientSupplier.apply(
>             GwClientSettings.builder().address(address).loopResources(clientLoopResources).build(),
>             op))
>         .startAwait();
> 
>     serviceCall = client.call().router(new StaticAddressRouter(address));
> ```
> 
> So, if I understood correctly, now to call gateway I need to do following steps on a _**caller side**_:
> 
> 1. Add dependency to whole `scalecube-services` module.
> 2. Build and start new `Microservices`.
> 3. Create `ServiceCall`.
> 
> Looks too overhead as for me.

there is no need for microservices. i have discussed this with ripa and we agreed its not required

2019-06-21 10:18 UTC, ronenhamias requested changes
client SDK is completely redundant

the changes should be made on service call.

it should be possible to instantiate a service call without router directlly to GW address.

```java
if(address!=null){ // making static call to api gateway
   return requestOne(request, responseType, address));
} else if (methodRegistry.containsInvoker(qualifier)) { // local service.
```  

```java
GreetingService service = ServiceCall.call().transport(<GatewayTransport>).address(address).api(GreetingService.class);
```

2019-06-22 08:10 UTC, artem-v requested changes
A `io.scalecube.services.ServiceCall` depends already on `scalecube-api` (in majority of imports). Only 
```
import io.scalecube.services.routing.RoundRobinServiceRouter;
import io.scalecube.services.routing.Routers;
```
tights us to `scalecube-services`.

It looks like `ServiceCall` can live in module `api` and if one needs talk to gateway he picks up gateway-client-transport and that's his dependencies.

2019-07-19 09:47 UTC, artem-v approved these changes

2019-07-19 09:48 UTC, merged