Ping mechanism on websocket gateway client (#94)
scalecube/scalecube-gateway pull request #95
Opened 2019-11-21 16:51 UTC by snripa

2019-11-22 08:19 UTC, dmytro-lazebnyi commented on services-gateway-client-transport/src/main/java/io/scalecube/services/gateway/transport/KeepaliveMessage.java
> +public class KeepaliveMessage {
`KeepaliveMessage` is redundant.

[Websocket specification (RFC 6455)](https://tools.ietf.org/html/rfc6455#section-5.5.2) defines that endpoint MUST send a `Pong` frame as a response to incoming `Ping` frame.

Both `netty` and `reactor-netty` supports this feature out of the box:
- netty 
https://github.com/netty/netty/blob/43252a61352f2785c19e321c67d5ac87aee4d172/codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketProtocolHandler.java#L48-L53
- reactor-netty
https://github.com/reactor/reactor-netty/blob/cadd13c11bb01d946164d61edb09a4bd472e0184/src/main/java/reactor/netty/http/server/WebsocketServerOperations.java#L147-L151

So, looks like it is enough just to send existing [PingWebsocketFrame](https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/websocketx/PingWebSocketFrame.java).

2019-11-22 10:20 UTC, artem-v requested changes

2019-11-22 10:20 UTC, artem-v commented on services-gateway-client-transport/src/main/java/io/scalecube/services/gateway/transport/KeepaliveSender.java
> +public class KeepaliveSender implements Runnable {
No need in this class. 
You can implement Runnable right in the WebsocketGatewayClient, and use it in [this block ](https://github.com/scalecube/scalecube-gateway/pull/95/files#diff-d4a33ef8f33409a906bd691f63f4d8d7R152-R155).

2019-11-22 10:20 UTC, artem-v commented on services-gateway-client-transport/src/main/java/io/scalecube/services/gateway/transport/GatewayClientSettings.java
> +  private final long keepaliveIntervalMs;
Could you make it as `Duration ` and [here](https://github.com/scalecube/scalecube-gateway/pull/95/files#diff-d4a33ef8f33409a906bd691f63f4d8d7R152-R155) convert to millis. In this case variable would be called just `keepaliveInterval`, and you wouldn't need to add `Ms` all over the places.

2019-11-26 10:47 UTC, dmytro-lazebnyi commented on services-gateway-client-transport/src/main/java/io/scalecube/services/gateway/transport/GatewayClientSettings.java
> +  private static final Duration DEFAULT_KEEPALIVE_INTERVAL = Duration.ofSeconds(30);
Do we need this default value?
So, am I right that ping-pong mechanism is enabled in any case?

2019-11-26 10:47 UTC, dmytro-lazebnyi commented on services-gateway-client-transport/src/main/java/io/scalecube/services/gateway/transport/GatewayClientSettings.java
> +     * Keepalive interval in ms. If client's channel doesn't have any activity at channel during
`ms` is redundant.

2019-11-26 10:47 UTC, dmytro-lazebnyi commented on services-gateway-client-transport/src/main/java/io/scalecube/services/gateway/transport/websocket/WebsocketGatewayClient.java
> +      AtomicReferenceFieldUpdater.newUpdater(
Looks like something changed in formatting. Could you please check the formatting settings?

2019-11-26 10:47 UTC, dmytro-lazebnyi commented on services-gateway-client-transport/src/main/java/io/scalecube/services/gateway/transport/websocket/WebsocketGatewayClient.java
> +                      .wiretap(true)
Maybe it is better to add an ability to configure it from the client's code using `GatewayClientSettings`.

2019-11-26 10:47 UTC, dmytro-lazebnyi commented on services-gateway-client-transport/src/main/java/io/scalecube/services/gateway/transport/websocket/WebsocketGatewayClient.java
> +                          .subscribe(avoid -> System.out.println("SENT PING"));
`System.out.println` is not good.

2019-11-26 10:47 UTC, dmytro-lazebnyi commented on services-gateway-client-transport/src/main/java/io/scalecube/services/gateway/transport/websocket/WebsocketGatewayClient.java
> +                              .subscribe(avoid -> System.out.println("SENT PING"));
`System.out.println` is not good.

2019-11-26 10:47 UTC, dmytro-lazebnyi commented on services-gateway-client-transport/src/main/java/io/scalecube/services/gateway/transport/websocket/WebsocketGatewayClient.java
> +            c ->
IMHO, `c` is less readable than `connection`.

2019-11-26 10:47 UTC, dmytro-lazebnyi commented on services-gateway-client-transport/src/main/java/io/scalecube/services/gateway/transport/websocket/WebsocketGatewayClient.java
> +            conn -> {
IMHO, `conn` is less readable than `connection`.

2019-11-26 13:33 UTC, dmytro-lazebnyi approved these changes

2019-11-26 13:35 UTC, dmytro-lazebnyi commented
:+1:

2019-11-26 17:29 UTC, segabriel commented on services-gateway-client-transport/src/main/java/io/scalecube/services/gateway/transport/websocket/WebsocketGatewayClient.java
> +                                  .subscribe(avoid -> {});
Please add the error handler to avoid CallbackNotImplemented

2019-11-26 17:29 UTC, segabriel commented on services-gateway-client-transport/src/main/java/io/scalecube/services/gateway/transport/websocket/WebsocketGatewayClient.java
> +                                  .subscribe(avoid -> {});
Please add the error handler

2019-11-27 07:12 UTC, artem-v approved these changes

2019-11-27 07:12 UTC, merged